### ISSUE TITLE
does not seem to generate all urls

### ISSUE THREAD

**Issue by shuat** [lgraubner/sitemap-generator#1]
This module looks great, but I just tried on my works site cardcash.com and it was missing most of the urls.

**Comment by lgraubner** [comment]
You are right. `https://www.cardcash.com/buy-gift-cards/`is ignored completely. Will have to figure out what's the problem.

**Comment by shuat** [comment]
@lgraubner Thanks. Let me know. When I have time I'll also try figure out why.

**Comment by jlvdh** [comment]
Having the same issues. Could it have something to do with clean urls?

**Comment by schiz** [comment]
I experience this issue to. Test on a site dir with ~ 1600 html pages, but the output was ~ 1400.

**Comment by lgraubner** [comment]
Could you check again with v5?

**Comment by lgraubner** [comment]
Fixed in #9.

**Comment by darinburris** [comment]
First off, love the module, has worked for me beautifully in almost every case.

Today, I did run into an interesting situation. When using the following, simple implementation, it never goes beyond the initial url.

```
var sitemapGenerator = require("sitemap-generator");
var generator = new sitemapGenerator('http://www.garageclothing.com/us');
generator.on(
    'fetch',
    function (status, url) {
        console.log('fetching: ',url, ' - status: ',status);
    }
);
generator.start();
```

Hoping to get your thoughts.

Cheers!

**Comment by lgraubner** [comment]
Your Website is just a wrapper for an iframe. Thats why the crawler can not find any links. A crawler is not able to jump "into" an iframe.
