### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by markadrake** [lgraubner/sitemap-generator#11]
Running the following code:

```
var SitemapGenerator = require('sitemap-generator');
 
// create generator
var generator = new SitemapGenerator('http://www.salamanderdesigns.com');
 
// register event listeners
generator.on('done', function (sitemaps) {
	console.log(sitemaps); // => array of generated sitemaps
});
 
// start the crawler
generator.start();
```

After approximately a minute it will exit with the following error: 

> RangeError: Maximum call stack size exceeded

Screenshot:

![image](https://cloud.githubusercontent.com/assets/713355/25634049/39b35e28-2f47-11e7-9ba4-f07d321dc623.png)

Should I raise this issue with **domelementtype**? 

> https://www.npmjs.com/package/domelementtype

**Comment by markadrake** [comment]
So I debugged this in Visual Studio Code and it pointed me somewhere else. Looks like **domutils** is the real culprit. So it may not be an issue with sitemap-generator. Anyone run into this issue using sitemap-generator though? 

![image](https://cloud.githubusercontent.com/assets/713355/25637992/e308b93e-2f54-11e7-9e57-cbab3d621271.png)

**Comment by lgraubner** [comment]
Looks indeed like a problem with `domutils`. All I can say is that this package is not used by `sitemap-generator` directly. I guess `cheerio` is using it as this is the module used for DOM parsing.
I'm afraid I can't help you here, try issuing the problem in the `cheerio` repo.
