### ISSUE TITLE
Set cookie before 'fetch'?

### ISSUE THREAD

**Issue by easingthemes** [lgraubner/sitemap-generator#12]
Hi,

Is there any way to set cookie before fetching event ?

Thanks.

**Comment by lgraubner** [comment]
The underlying crawler [supports this](https://github.com/cgiffard/node-simplecrawler#cookies), but this is not implemented for sitemap-generator yet. Feel free to send a PR.

**Comment by lgraubner** [comment]
What I said is wrong. It's not possible to manually add cookies, but it collects cookies and resends them. You could check the User Agent and add cookies after the first request.
