### ISSUE TITLE
Add a UA string option

### ISSUE THREAD

**Issue by NKjoep** [lgraubner/sitemap-generator#13]
Add a field to feed the simple crawler.

```js
  // sitemap-generator/lib/SitemapGenerator.js:142

  // set user agent
  this.crawler.userAgent = this.options.ua || 'Node/SitemapGenerator';

```

so we could do this:

```js
// create generator
var generator = new SitemapGenerator('some-url.com', {
  ua: 'my custom crawler'
});

```

**Comment by lgraubner** [comment]
Why you need to set a custom User Agent?

**Comment by NKjoep** [comment]
To trigger different services the same way I already trigger the GoogleBot crawler.

I serve to crawlers lighter and easier to parse pages in order to speed up the process and save bandwidth.

**Comment by lgraubner** [comment]
So you are using the crawler to trigger actions on your system? Sounds like this is not the right tool for this.

**Comment by NKjoep** [comment]
no. I want to use the crawler as a crawler and I need to be able to intercept it the same way you should intercept GoogleBot, bingbot e so many others.

Also I don't want to change the configuration already in place, so configuring this sitemap generator to be recognisable as a GoogleBot would be enough.

There are several other scenarios also, single page app or website with no server side rendering.

**Comment by lgraubner** [comment]
Okay, so you want to redirect the sitemap generator to a different page than visitors, right? Why not just add the current UA to your redirect list as well? I guess that wouldn't be too hard.

I'm trying to evaluate if this addition is worth to be added. I don't want to offer too much configuration to keep it simple. This seems to be a rarely needed case which can be fixed on your side as well. Technically this would be easy to implement as you already figured out.

**Comment by lgraubner** [comment]
Implemented an `userAgent` option. Should suit your needs.
