### ISSUE TITLE
Rename fails across different filesystems

### ISSUE THREAD

**Issue by fmujakitz** [lgraubner/sitemap-generator#16]
https://github.com/lgraubner/sitemap-generator/blob/00ce03a4e9a21ef6ca9761df15cba41f462f2e7c/lib/index.js#L153

Rename is low level, and this doesn't work, so copy and remove.

Cheers!

**Comment by lgraubner** [comment]
Why should this not work? This is a standard Node.js fs method which works cross platform. Do you have a specific problem? What OS are you using?

**Comment by fmujakitz** [comment]
Yes, it's relatively specific issue. Low level rename cannot work across different filesystems. It's just not built that way. Maybe I'm wrong, afaik no OS supports that. 

I'm using ubuntu, ext4 fs, with multiple partitions and multiple mount points. The plugin streams the sitemap to a file located at /tmp then it tries to rename it to /path/to/filename. Since /tmp is on mountpoint1, and rename tries to re-link it to mountpoint2, it silently fails.

**Comment by lgraubner** [comment]
I created the branch [fix/rename](https://github.com/lgraubner/sitemap-generator/tree/fix/rename) which replaces `fs.rename` with `cp-file` + `fs.unlink`. Thats what you suggested, right?
Could you check it out and test on your system? I don't have a Ubuntu box here right now, would have to spin up one first.

**Comment by fmujakitz** [comment]
Yes, that's what I suggested. It's resolved while splitting multiple sitemaps per maxEntriesPerFile, but still not resolved with single sitemap. Same approach should be ok.

**Comment by lgraubner** [comment]
Fixed in 8b46d53. New Version available. :)
