### ISSUE TITLE
htaccess :  Authorization User/Password

### ISSUE THREAD

**Issue by mleathem** [lgraubner/sitemap-generator#22]
Is there a way to pass Authorization in - so a site can be crawled behind password protected htaccess ?
If not can I put in a feature request please?

--
_PS. Loving the work...! very helpful - Thanks_

**Comment by lgraubner** [comment]
Now it is! Just released v7.5 which contains appropriate options. I already thought this would be useful but till now I didn't need it and no one requested it.

So please check it out (details in README) and report any problems. :)

**Comment by mleathem** [comment]
great thanks!
works fine ( _once I remembered to update!_ )
