### ISSUE TITLE
Crawler Add Fetch Condition

### ISSUE THREAD

**Issue by guga-grigolia** [lgraubner/sitemap-generator#31]
Feature.

Hi I want to use simplecrawler's [Add Fetch Condition](https://github.com/simplecrawler/simplecrawler#adding-a-fetch-condition) functionality and I was not able to pass my own exclusions or override existing ones. If there is some possibility I'd be really thankful if you will point it out for me, or I can create PR for that.

Regards,
Guga

**Comment by lgraubner** [comment]
At the moment this is not possible, but can be easily added.

I'm thinking of something like `generator.getCrawler()` to expose the simplecrawler instance. That way you can easily add new fetch conditions. How does this sound?

**Comment by guga-grigolia** [comment]
Yes, it sounds quite promising. Thanks a lot.

**Comment by lgraubner** [comment]
Just released v8.1.0 which provides a `getCrawler()` method. I hope it helps :)

**Comment by arboshiki** [comment]
I think the tag is not published on npmjs.com. I can not install that tag through npm.

**Comment by lgraubner** [comment]
My bad, seems to have been errored without me noticing. Should be out now for real.

**Comment by arboshiki** [comment]
Thank you
