### ISSUE TITLE
[Question]: How do you disable the sitemap.xml file creation?

### ISSUE THREAD

**Issue by neorganic** [lgraubner/sitemap-generator#32]
Also looked in the crawler documentation for keywords, but seems that it is not mentioned.

**Comment by lgraubner** [comment]
The purpose of this tool is to generate an sitemap, therefore you can't disable it. You could write the file to `/tmp` which would be deleted on machine restart.

**Comment by neorganic** [comment]
Thanks !

**Comment by lgraubner** [comment]
Even better. :)
