### ISSUE TITLE
doesn't support js rendered sites

### ISSUE THREAD

**Issue by neorganic** [lgraubner/sitemap-generator#33]
It doesn't seem to support sites like e.g. builded with wix.com website builder

**Comment by lgraubner** [comment]
Probably related to #34. Working fine for me. If this doesn't solve your problem post your code and reopen.

**Comment by neorganic** [comment]
Yeah same code - different outputs depending on the testing dates - some inconsistency with the site itself I guess, which I yet still to find out/debug.

**Comment by lgraubner** [comment]
Interesting. Maybe sometimes facing a server rendered page and sometimes a dynamic one? Server rendering should be by definition not be a problem.
