### ISSUE TITLE
Define "lastmod" on "queueURL"

### ISSUE THREAD

**Issue by rtyx** [lgraubner/sitemap-generator#36]
**Do you want to request a *feature* or report a *bug*?**

I would like to know if it's possible (or if it can be implemented) to specify the lastmod property on queueURL.

**What is the current behavior?**

Currently queueURL only adds the URL without specifying a lastmod date different from the global one.

**What is the expected behavior?**

Ideally, when queuing a URL you could pass the datemod as a parameter, such as:

`                generator.queueURL(url, datemod);`

**Comment by lgraubner** [comment]
Not sure if `queueURL` is the right place to specify lastmod. It's just a hint to what the crawler should look for and the sitemap is generated afterwards.

Maybe we could add some kind of map to map lastmod dates to URLs.

**Comment by neorganic** [comment]
Keep in mind that not all sites support/provide lastmod  data.

**Comment by lgraubner** [comment]
I'm fully aware of this. Anyway there is no easy way to provide data like this for a crawler.

**Comment by lgraubner** [comment]
Generally I'm open for a good solution to provide lastmod data, but your proposed one doesn't seem like a good fit. If you have a better idea please reopen or create a new issue.

Closing this issues.
