### ISSUE TITLE
Option to use last-modified header for <lastmod>

### ISSUE THREAD

**Issue by Lingonmirakel** [lgraubner/sitemap-generator#37]
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
`lastMod` is a boolean, and will always use today’s date if set to true.

**What is the expected behavior?**
According to https://webmasters.googleblog.com/2014/10/best-practices-for-xml-sitemaps-rssatom.html the last modification time should be "the last time the content of the page changed meaningfully". I would like to be able to use the response’s `last-modified` header instead of today’s date for `<lastmod>`.

**Comment by lgraubner** [comment]
That's probably the best way to go. Maybe I have some spare time this week and can implement it.

**Comment by lgraubner** [comment]
Implemented it as stated above (ff3022f6d519dbfe5ec0fc1bda431318d535d19a), new release is out!

**Comment by Lingonmirakel** [comment]
Well done, thanks Lars!
