### ISSUE TITLE
[Request] option to disable sitemap generating. 

### ISSUE THREAD

**Issue by neorganic** [lgraubner/sitemap-generator#38]
I am using a custom usage of this package to console log the sitemap links .... and to store them to DB. The sitemap generation is causing me various issues. The ````/dev/null```` doesn't seem to work well enough in some cases.

Would be great if there would be a way just to disable the output of the sitemap.xml

**Comment by lgraubner** [comment]
There might be some use cases. We could simply disable file generation by setting `filepath` to `null`. I'm gonna look into that this week.

**Comment by lgraubner** [comment]
Added the behavior describe aboved (de189ba125a3c1a275403bf3e9959910a1d440ea), check out the new release.
