### ISSUE TITLE
.pdf file is included in the sitemap.

### ISSUE THREAD

**Issue by neorganic** [lgraubner/sitemap-generator#40]
For http://hkida.net/  it gets http://hkida.net/Areas/Client/Content/Doc/BENEFITS.pdf as part of the sitemap, which I believe does not belong here.

**Comment by lgraubner** [comment]
It does belong there as Google is able to parse PDF files (see full list: https://support.google.com/webmasters/answer/35287?hl=en). Also check out this StackOverflow answer: https://stackoverflow.com/a/3816174

If you still don't want it in your sitemap you can add a fetch condition and exclude PDF. (see #31)
