### ISSUE TITLE
fails to generate a sitemap of https://www.kuleuven.be/english/ 

### ISSUE THREAD

**Issue by neorganic** [lgraubner/sitemap-generator#43]
returns
```
Sitemap scan doesn't found any pages 
sitemap scan has finished 
```

**Comment by lgraubner** [comment]
Could you please provide some code to reproduce?

**Comment by neorganic** [comment]
Actually can't reproduce the issue anymore. Hopefully, there was an issue with my code, which is now fixed or site had some issues.
