### ISSUE TITLE
Can someone help me with the detailed instruction ?

### ISSUE THREAD

**Issue by agnaveen** [lgraubner/sitemap-generator#48]
I could not understand the steps mentioned here.

I would like to know more details like what to be imported in appmodule, where to put the code blog and stuffs like that.

But I could not get these details here, if documentation is improved little bit then more people like me can also experience this nice plugin.

**Comment by lgraubner** [comment]
I improved the README and added a more detailed introduction as well as an FAQ. Please tell me if there is still something unclear.
