### ISSUE TITLE
Regex for AMP matches normal pages

### ISSUE THREAD

**Issue by bjoernbg** [lgraubner/sitemap-generator#49]
Hi,

we had a problem that the option ignoreAMP (default: true) caused normal, valid pages to be ignored as well. This seems to be an issue specific to pages with minified html. As an example you can try with:
https://www.ergosign.de/en/news/2018/event-uxcamp-switzerland.html

This page should not be ignored. The cause was difficult to debug, so maybe the reason for ignoring a page could be added to the 'ignore' event…

Thx for this great tool!

Björn

**Comment by lgraubner** [comment]
You are right. I improved the regex. Release will follow soon. :)
