### ISSUE TITLE
Not working from localhost:9090

### ISSUE THREAD

**Issue by joecarney** [lgraubner/sitemap-generator#5]
I'd like to test on a local version of my site and all it is returning is null...

```
var generator = new SitemapGenerator('http://localhost', {
  port: 9090,
  restrictToBasepath: true,
  stripQuerystring: false
});
```

If I try a...

`curl http://localhost:9090` 

I can see my html being returned.

Any ideas why it cannot generate sitemaps from localhost?

**Comment by joecarney** [comment]
I've checked my local `robots.txt` and it is fine:

```
User-agent: *
Allow: /
```

Also, the only output I see from the crawl is:

```
node sitemap.js
fetch:
http://localhost:9090/
done:
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"/>
```

I'm thinking it could be because my urls do not contain the full domain inside them?

For example, an `href` for my Contact page is `/contact` and not `http://localhost:9090/contact`

**Comment by lgraubner** [comment]
`localhost` shouldn't be a problem and relative URL's are fine. I'd suggest adding event logging for debug purposes:

```JavaScript
generator.on('fetch', function (status, url) {
  console.log(status, url);
});

generator.on('clienterror', function (queueError, errorData) {
  console.log(queueError, errorData);
});

generator.on('ignore', function (url) {
  console.log('ignore', url);
});
```

You should see what's the problem. If this does not clarify post the output here.

**Comment by lgraubner** [comment]
Localhost should not be a problem, there might have been a problem with the custom port. Version 5 fixed a couple problems regarding ports.
