### ISSUE TITLE
Working with schedule events (replacing sitemap file) WRITE ERROR.

### ISSUE THREAD

**Issue by vitorregisrr** [lgraubner/sitemap-generator#59]
[BUG]

**Expected**
I'm trying to create a schedule sitemap-gen. The idea is starting a loop in the server, that every 12hours, should update an EXISTENT sitemap.xml in a dir.
For the loop, i'm using the package "node-cron", whose works like node-schedule. It's a simple package to create timed events.
The scope that i'm working on is:

```
//obvions importing packages like const a = require('a') for everything
 
// creatint generator etc
const generator = SitemapGenerator('http://www.planagroimoveis.com.br', {
  stripQuerystring: false,
  filepath: './app/public/sitemap.xml',
});
 
generator.on('done', (resul) => {
    console.log('Sitemap atualizado.')
});

//starting the timed event, that for test will repeat every 50 seconds (to better debbug it)
nodeCron.schedule('*/50 * * * * *', function () {
   sitemapGenerator.start();
});
```
**Buut... The error is:**
The first time that the schedule is called works fine, but in the second, i receive the error
```
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:243:12)
    at WriteStream.Writable.write (_stream_writable.js:291:5)
    //and a lot of things more, i dont think it's necessary
```

I think the problem isn't with replacing an existing file, because i've already tryied to delete it (with fs.unlink) before start the generator.

**Comment by lgraubner** [comment]
Could you try to create a new SitemapGenerator instance each time? I think that should work. Otherwise it probably tries to write to the same temporary file.

**Comment by vitorregisrr** [comment]
> Could you try to create a new SitemapGenerator instance each time? I think that should work. Otherwise it probably tries to write to the same temporary file.

Perfect! Thank you very much bro.
