### ISSUE TITLE
Expose addURL interface

### ISSUE THREAD

**Issue by xChrisPx** [lgraubner/sitemap-generator#60]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
URLs can only be added to crawler queue, not the sitemap stream directly
**If the current behavior is a bug, please provide the steps to reproduce.**
N/A
**What is the expected behavior?**
I have thousands of pages that I create straight from the database. I do not need them to be crawled, which takes hours using this package. I guess the easiest way to fix this, would be to just expose the `addURL` function on the sitemap.

I cloned this repo and fixed it locally. If you make me a contributor I can quickly submit a PR.

**Comment by ellioseven** [comment]
@xChrisPx There is a PR here: https://github.com/lgraubner/sitemap-generator/pull/61

**Comment by lgraubner** [comment]
Solved with #61
