### ISSUE TITLE
Feature request, Duplicate page detector

### ISSUE THREAD

**Issue by mlibre** [lgraubner/sitemap-generator#70]
**Do you want to request a *feature* or report a *bug*?**
feature.
Adding duplicate link/page detection could be a good idea.
Google detects duplicate pages even if the page would not have the canonical references.
You are already crawling the page. you can make a hash of the content of each page, store it in an array.
whenever you want to add a link to sitemap.xml, first you need to make sure if there is no same hash in the array

**Comment by lgraubner** [comment]
The crawler should not add duplicate pages.

**Comment by mlibre** [comment]
Even the same pages with different urls?
like:
* a.com/urla
* a.com/urlb
And they are both exact same page
or:
* a.com/url
* a.com/url?hit=hi
