### ISSUE TITLE
Feature request  / docs addition - Replace localhost with web address

### ISSUE THREAD

**Issue by jondo89** [lgraubner/sitemap-generator#75]
Hi , Please could you add a feature/explain how to replace the localhost site generator with the final hosting address on the generated maps.

i.e

  <url>
    <loc>http://localhost:5000/</loc>
  </url>

replace with

  <url>
    <loc>http://finaldestination.etc/</loc>
  </url>

**Comment by lgraubner** [comment]
That sounds useful. Anyone willing to submit a PR for this?

**Comment by lgraubner** [comment]
Duplicate of #65 closing this here.
