### ISSUE TITLE
Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

### ISSUE THREAD

**Issue by Jonarhipov** [lgraubner/sitemap-generator#81]
**Do you want to request a *feature* or report a *bug*?**
IDK
**What is the current behavior?**
When I'm trying to crawl my website via https I'm getting warning and the stop of the process.
`Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.`
Using with http is working.

Can anyone explain what is a problem?

**Comment by lgraubner** [comment]
https://nodejs.org/api/cli.html#cli_node_tls_reject_unauthorized_value

The purpose this is used is to allow sitemap generation for development sites which might have non secure SSL certificates. I might factor this out and put this in the responsibility of the user.

You can ignore this.
